### ISSUE TITLE
Warning: file_get_contents...stable_joomla_releases.txt

### ISSUE THREAD

**Issue by infograf768** [infograf768/j4localise#46]
@Valc 
Clean first com_localise installation.
First displaying the Translations page after selecting a language and a client (did not go to Options to `Enable development reference language`)

I get a warning
<img width="1545" alt="Screen Shot 2021-11-11 at 10 32 12" src="https://user-images.githubusercontent.com/869724/141274788-4d8f1670-7590-4023-b3e8-48a1e67744d6.png">

The reason is that this file does not exist yet. I guess we should first check `$allow_develop`, but something is confusing for me: we can't have already `$gh_data`.

In the TranslationsModel, we have, also without checking if `gh_allow_develop` is set to Yes:
```
$gh_data = array();
			$gh_data['github_client'] = $filter_client;

			$get_github_files   = LocaliseHelper::getTargetgithubfiles($gh_data);
			$get_customised_ref = LocaliseHelper::getSourceGithubfiles($gh_data);
```
Any idea to solve this in a clean way?

**Comment by Valc** [comment]
@infograf768
These are different issues.

From the view in 'translations' we must obtain the changes that have occurred in the language files to be able to show them in the table or list of the language files that we can later edit one by one.

That includes the set by client selectd of development files to download from Github, which really only needs to be done when 'Allow develop' is enabled.

Note than that code part will simply ensure than we get the set of files from Github and if 'Allow develop' is enabled the is displayed the 'Development info on translations table' on each file to translate, if is present.

If not 'Allow develop' enabled then that 'Development info' is not displayed.

The warnings actually occur because the code is trying to get the content from files that have not yet been created, but will be.

Both cases seems that are easy to solve, i will prepare the PR now.

**Comment by infograf768** [comment]
@Valc 
Rafael, I guess this can be closed.
released RC1
https://github.com/infograf768/j4localise/releases/tag/5.0.0-RC1

**Comment by Valc** [comment]
@infograf768
Yep. It can be closed.
We are at RC! Thank you :)
